#!/usr/bin/env python3
import roll as r
Intelligence=r.roll(2,5)
Strength=r.roll(2,5)
Wisdom=r.roll(2,5)
Agility=r.roll(2,5)
Luck=r.roll(2,5)
Charisma=r.roll(2,5)
Dexterity=r.roll(2,5)
Tenacity=r.roll(2,5)
print('Intelligence:'+str(Intelligence))
print('Strength:'+str(Strength))
print('Wisdom:'+str(Wisdom))
print('Agility:'+str(Agility))
print('Luck:'+str(Luck))
print('Charisma:'+str(Charisma))
print('Dexterity:'+str(Dexterity))
print('Tenacity:'+str(Tenacity))
